[최명준] 상세페이지 리뷰 엔드포인트 구현
wecode-bootcamp-korea/22-2nd-upoonGallery-backend pull request #10
Opened 2021-07-26 15:29 UTC by junlegend

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)

- 상세페이지 리뷰 엔드포인트 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

ReviewView 생성
- post, get http 메소드로 리뷰 작성 및 불러오기 구현 
- s3를 이용한 이미지 업로드 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-26 15:40 UTC, junlegend commented
<img width="1013" alt="ReviewView_POST" src="https://user-images.githubusercontent.com/78292900/127017833-0c5c6ed3-eb50-4b25-b41d-78c7c15c9bd9.png">

<img width="1189" alt="ReviewView_GET" src="https://user-images.githubusercontent.com/78292900/127017853-7b058914-0f20-4dbc-914d-ee6103a6d5e1.png">

2021-07-27 01:02 UTC, Kang-kyunghun requested changes

2021-07-27 01:02 UTC, Kang-kyunghun commented on .vscode/settings.json
> +{
제거하고 gitingore에 추가해 주세요.

2021-07-27 01:02 UTC, Kang-kyunghun commented on reviews/views.py
> +            reviews = Review.objects.filter(art=art)
```suggestion
            reviews = Review.objects.filter(art_id=art_id)
```
art_id를 알고 있으므로, 알고 있는 id를 활용하면 좋습니다~

2021-07-27 01:02 UTC, Kang-kyunghun commented on reviews/views.py
> +            } for review in reviews]
:을 기준으로 정렬해 주셍요.

2021-07-27 01:02 UTC, Kang-kyunghun commented on reviews/views.py
> +    @login_required
정렬이 하나도 안 되어 있습니다. =, : 을 기준으로 정렬해 주세요.

2021-07-27 01:02 UTC, Kang-kyunghun commented on reviews/views.py
> +
다음과 같이 에러처리를 할경우 코드의 상세 정보까지 유출될 가능성이 있어 보안에 좋지 않습니다. 
제거해 주시고, 일어날 수 있는 예외처리를 정확히 해주세요.

2021-07-27 01:02 UTC, Kang-kyunghun commented on reviews/views.py
> +            )
리뷰의 이미지가 하나만 올라가나요?

2021-07-27 01:02 UTC, Kang-kyunghun commented on reviews/views.py
> +            )
s3 설정 같은 경우는 해당 view 이외의 곳에서도 사용 할 수 있습니다. 따라서 외부로 따로 빼서 class로 정의하는 것이 좋습니다.
class로 정의 할 경우 재사용성도 좋고 unittest 할 때도 편해 집니다.

2021-07-27 15:14 UTC, junlegend commented on reviews/views.py
> +            image_file_name = uuid.uuid1().hex
같은 이름을 가진 서로 다른 파일이 업로드 될 수 있게 하려고 uuid를 사용했습니다.
uuid1은 현재 시간으로 uuid를 생성하므로 중복의 가능성이 적을 것 같아서 사용했고, 

uuid로 나온 값의 포맷이 숫자와 하이픈이 결합된 형태여서인지 s3에 업로드 되지않아
서칭을 통해 hex 메소드를 사용해 스트링 형태로 바꾼 사례를 발견하고 
hex 메소드를 사용해봤습니다.

2021-07-28 02:18 UTC, junlegend commented on reviews/views.py
> +            )
하나만 업로드 하는 것으로 논의했던거라 우선 1개를 업로드하는 것으로 진행하고
여유가 되면 여러 파일을 업로드 할 수 있는 방법을 공부해보겠습니다, 감사합니다!

2021-07-28 02:18 UTC, junlegend commented on reviews/views.py
> +
수정했습니다, 감사합니다!

2021-07-28 02:18 UTC, junlegend commented on reviews/views.py
> +    @login_required
전체적으로 컨벤션 수정했습니다, 감사합니다!

2021-07-28 02:18 UTC, junlegend commented on reviews/views.py
> +            reviews = Review.objects.filter(art=art)
수정했습니다, 감사합니다!

2021-07-28 02:18 UTC, junlegend commented on .vscode/settings.json
> +{
제거하고 gitignore에 추가했습니다, 감사합니다!

2021-07-28 02:42 UTC, junlegend commented on reviews/views.py
> +            )
알려주셔서 감사합니다!
나중에 꼭 만들어 보겠습니다!!

2021-07-28 06:51 UTC, Kang-kyunghun requested changes

2021-07-28 06:51 UTC, Kang-kyunghun commented on reviews/views.py
> +            return JsonResponse({'message': 'INVALID_KEY'}, status=400)
1. key error가 발생하는 상황이 있나요?
2. get method에 대해서는 unit test 추가해 주세요.

2021-07-28 06:51 UTC, Kang-kyunghun commented on reviews/views.py
> +            image_file_name = uuid.uuid1().hex
uuid 잘 사용하셨습니다. str로 바꾸기 위함이였다면, str() method을 사용해도 좋을 것 같아요.
그리고 정렬은 꼭 확인해 주세요.
```suggestion
            image_file      = request.FILES['image_file']
            image_file_name = str(uuid.uuid1())
```

2021-07-28 18:38 UTC, junlegend commented on reviews/views.py
> +            } for review in reviews]
수정했습니다, 감사합니다!

2021-07-28 18:40 UTC, junlegend commented on reviews/views.py
> +            return JsonResponse({'message': 'INVALID_KEY'}, status=400)
KeyError 발생하지 않아 수정했습니다.
get method 에 대한 unit test 추가했습니다.
감사합니다!

2021-07-28 18:41 UTC, junlegend commented on reviews/views.py
> +            image_file_name = uuid.uuid1().hex
네~ 정렬 수정했고 str() method로 수정했습니다, 감사합니다!

2021-07-28 18:44 UTC, junlegend commented on reviews/views.py
> +            return JsonResponse({'message': 'INVALID_KEY'}, status=400)
<img width="855" alt="스크린샷 2021-07-29 오전 1 33 57" src="https://user-images.githubusercontent.com/78292900/127378542-eb61398a-43e0-4f7a-9545-0c482894a4fd.png">

2021-07-28 19:07 UTC, 93-0312 commented
명준님 안주무셨군요..

2021-07-29 05:19 UTC, Kang-kyunghun requested changes

2021-07-29 05:19 UTC, Kang-kyunghun commented on reviews/views.py
> +            )
```suggestion
            if not Art.objects.filter(id=art_id).exists():
                return JsonResponse({"message" : "NOT_FOUND"}, status=404)

            review = Review.objects.create(
                user_id = user.id,
                art_id  = art_id,
                comment = request.POST.get("comment")
            )
```
art_id의 존재 유무를 먼저 판단해야 합니다. 그래서 만약 id가 존재하지 않으면, 에러를 보내주어야 합니다. 그리고 존재 할 경우는 이미 id를 알고 있으므로 get을 통해 객체를 불러올 필요없이 바로 id를 활용해 주면 될 것 같습니다.

2021-07-29 05:40 UTC, junlegend commented on reviews/views.py
> +            )
filter().exists() 메소드를 사용하는 것으로 수정했습니다, 감사합니다!

2021-07-29 07:03 UTC, Kang-kyunghun commented
LGTM~~ 고생 많으셨습니다~~

2021-07-29 07:03 UTC, merged