[김예랑] feature/users
wecode-bootcamp-korea/22-2nd-upoonGallery-backend pull request #4
Opened 2021-07-22 02:44 UTC by Yerang-Kim

Add: users/views.py, core/utils.py
add SignIn/Up api with KakaoApi, Decorator(login_required)
add SignOut api with KakaoApi, SignBye api 

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카카오 로그인 API 이용한 유저 뷰 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 카카오 api 이용 로그인 
- 첫 로그인시 데이터베이스에 회원정보 저장(회원가입)
- 카카오 api 이용 로그아웃 
- 회원탈퇴(SignByeView) 뷰 작성 (softdelete)
- 토큰 검사 데코레이터 작성 => core/utils.py => login_required 함수

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-  

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-23 01:17 UTC, Kang-kyunghun requested changes

2021-07-23 01:17 UTC, Kang-kyunghun commented on upoon_galley/settings.py
> +# }
사용하지 않는 코드는 지워주세요.

2021-07-23 01:17 UTC, Kang-kyunghun commented on core/utils.py
> +        return func(self, request, *args, **kwargs)
exception 위로 올려주세요

2021-07-23 01:17 UTC, Kang-kyunghun commented on users/views.py
> +            }
```suggestion
            headers = {'Authorization': f'Bearer {kakao_access_token}'}
```
이정도 길이는 한 줄로 쓰는 것이 더 가독성에 좋습니다.

2021-07-23 01:17 UTC, Kang-kyunghun commented on users/views.py
> +            )
get_or_create을 사용할 경우 해당 데이터를 특정 지울 수 있는 것으로 먼저 체크 후 생성 되었을 때 데이터를 넣어 주어야 합니다.
```suggestion
            user, is_created =  User.objects.get_or_create(kakao_id  = kakao_id)
            
            if is_created:
                user.email     = email,
                user.nick_name = nick_name,
                user.birthday  = birthday,
                user.gender    = gender
                user.save()
``` 
또는 default 옵션을 사용할 수 있는데, 이 부분은 공식 문서를 참고해 보세요.

2021-07-23 01:17 UTC, Kang-kyunghun commented on users/views.py
> +                return JsonResponse({'access_token': access_token}, status=201)
user가 생성 되었든 아니든 token을 보내주어야 하기 때문에 불필요해 보입니다.

2021-07-23 01:17 UTC, Kang-kyunghun commented on users/views.py
> +                user.restore()
이 부분은 로그인에 포함하기 보다는 삭제후 복원하는 api가 따로 있어야 할 것 같아요

2021-07-23 01:25 UTC, Yerang-Kim commented on upoon_galley/settings.py
> +# }
로깅 잠시 주석처리 해놓았는데 앞으로 쓰는게 좋을 것 같아서 주석 해제했습니다!!

2021-07-23 01:26 UTC, Yerang-Kim commented on users/views.py
> +            }
넵 수정햇습니다!

2021-07-23 01:28 UTC, Yerang-Kim commented on users/views.py
> +            )
넵 반영했습니다!! 문서도 참고해보겠습니다

2021-07-23 01:33 UTC, Yerang-Kim commented on users/views.py
> +                return JsonResponse({'access_token': access_token}, status=201)
넵 반영했습니다! 
혹시 생성된 경우와 읽은 경우에 상태코드는 달리 해줄 필요는 없나요?
엑세스 토큰 생성해서 보내주는 것이 동일하니까 같은 상태코드로 보내주면 되는건가요?

2021-07-23 01:33 UTC, Yerang-Kim commented on users/views.py
> +                user.restore()
넵 삭제했습니다!

2021-07-23 01:35 UTC, Yerang-Kim commented on core/utils.py
> +        return func(self, request, *args, **kwargs)
넵 수정했습니다~!

2021-07-23 01:41 UTC, Yerang-Kim commented
리뷰 주신 부분들 반영후 푸쉬했습니다. 
유닛 테스트 작성 완료하면 다시 푸쉬하겠습니다~!

2021-07-23 04:40 UTC, Kang-kyunghun commented
생성 되었을 때와 db에서 가져왔을 때랑 이후 동작의 구분이 필요한 상황이라면 구분이 필요합니다. 결과적으로 해당 뷰는 login을 위한 view이기 때문에 통일해도 무방할 것 같아요.

2021-07-23 07:50 UTC, Kang-kyunghun requested changes

2021-07-23 07:50 UTC, Kang-kyunghun commented on users/tests.py
> +
setup에서는 제거해 주세요.

2021-07-23 08:25 UTC, Yerang-Kim commented on users/tests.py
> +
넵 제거햇습니다

2021-07-26 01:38 UTC, Kang-kyunghun requested changes

2021-07-26 01:38 UTC, Kang-kyunghun commented on users/tests.py
> +        self.assertEqual(user.kakao_id, "333")
위의 새로운 유저의 경우 db에 생성 될 id가 불명확하여 user의 kakao_id로 확인하는 것은 괜찮은 것 같습니다.
그러데, 이미 있는 유저 같은 경우에는 user_id를 확실히 알 수 있으므로 jwt decode가 아닌, 우리고 알고 있는 id를 가지고 token을 만든 뒤에 실제 view의 return값과 같은지 비교하는 것이 좋을 거 같습니다.

2021-07-26 05:59 UTC, Yerang-Kim commented on users/tests.py
> +        self.assertEqual(user.kakao_id, "333")
넵 반영했습니다.

2021-07-26 07:00 UTC, Kang-kyunghun commented
LGTM~~!!!

2021-07-26 07:01 UTC, merged