[최현정] 작품 필터링 구현
wecode-bootcamp-korea/22-2nd-upoonGallery-backend pull request #7
Opened 2021-07-22 10:56 UTC by princenim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 작품 필터링 뷰 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-23 01:20 UTC, Kang-kyunghun commented
1. q()를 하나로 통일 시켜서 구현해 보세요.
2. 일단 artist 부분은 제외 시키고 구현해 보세요.

2021-07-23 10:47 UTC, princenim commented
> 1. q()를 하나로 통일 시켜서 구현해 보세요.
> 2. 일단 artist 부분은 제외 시키고 구현해 보세요.

2021-07-23 10:48 UTC, princenim commented
> 1. q()를 하나로 통일 시켜서 구현해 보세요.
> 2. 일단 artist 부분은 제외 시키고 구현해 보세요.

수정했습니다!!!

2021-07-23 10:49 UTC, princenim commented
수정했습니다!

2021-07-26 08:10 UTC, Kang-kyunghun requested changes

2021-07-26 08:10 UTC, Kang-kyunghun commented on upoon_galley/settings.py
> +# }
github에 올라오는 코드에는 디버그 관련 코드는 삭제해 주세요. 코드 성능을 저하 시킵니다.

2021-07-26 08:10 UTC, Kang-kyunghun commented on arts/views.py
> +            total_count = len(arts)
django ORM 중에 count() method가 있습니다. 활용해 보세요.

2021-07-26 08:10 UTC, Kang-kyunghun commented on arts/views.py
> +            return JsonResponse({'message': 'ART_NOT_FOUND'}, status=400)
404가 더 적절할 것 같습니다.

2021-07-26 08:10 UTC, Kang-kyunghun commented on arts/views.py
> +        art_info = {
infor -> information

줄임말 자제해 주세요.

2021-07-26 08:10 UTC, Kang-kyunghun commented on arts/views.py
> +                q.add(Q(artist__name = artist_name), q.AND)
이름으로 필터링이랑 Q 적용까지 잘 하셨습니다~~!!

2021-07-26 08:10 UTC, Kang-kyunghun commented on arts/views.py
> +                } for art in arts[ offset : offset + limit]
페이지네이션을 적용할 때 어떻게 계산하면 좋을지 한 번 더 생각해 보세요. 
보통 offset은 page, limit은 page당 갯수를 의미합니다.

2021-07-26 08:10 UTC, Kang-kyunghun requested changes

2021-07-26 08:10 UTC, Kang-kyunghun commented on arts/views.py
> +class ArtDetailView(View):
```suggestion
class ArtView(View):
```

2021-07-26 14:48 UTC, princenim commented on upoon_galley/settings.py
> +# }
수정했습니다!

2021-07-26 14:49 UTC, princenim commented on arts/views.py
> +            return JsonResponse({'message': 'ART_NOT_FOUND'}, status=400)
수정했습니다!

2021-07-26 14:50 UTC, princenim commented on arts/views.py
> +        art_info = {
수정했습니다.

2021-07-26 14:54 UTC, princenim commented on arts/views.py
> +                q.add(Q(artist__name = artist_name), q.AND)
🙌🙌🙌🙌 감사합니다~

2021-07-26 15:03 UTC, princenim commented on arts/views.py
> +            total_count = len(arts)
수정했습니다~

2021-07-26 15:39 UTC, princenim commented on arts/views.py
> +class ArtDetailView(View):
수정했습니다!

2021-07-27 07:16 UTC, princenim commented on arts/views.py
> +                } for art in arts[ offset : offset + limit]
수정했습니다!

2021-07-28 09:26 UTC, Kang-kyunghun commented
LGTM~~!!

2021-07-28 09:26 UTC, merged